### ISSUE TITLE
markdown formatting nitpicks

### ISSUE THREAD

**Issue by aliceriot** [leucos/ansible-tuto#77]
If you do fenced code blocks instead of indenting github will highlight the yaml - as is the included files are readable in the editor but the README on the browser isn't very attractive. Compare the following:

    - hosts: web
      tasks:
        - name: Installs apache web server
          apt: pkg=apache2 state=installed update_cache=true

```yaml
- hosts: web
  tasks:
    - name: Installs apache web server
      apt: pkg=apache2 state=installed update_cache=true
```

I think the fenced code blocks greatly enhance readability - I'm reading the tutorial README's on github while following along in the terminal.

I'm willing to submit a PR which makes this change!

Thanks for writing a great tutorial!
